### ISSUE TITLE
Cannot read property 'tokenCache' of undefined

### ISSUE THREAD

**Issue by yhersh** [serverless/serverless-azure-functions#68]
Hello,

I have followed the [azure quickstart guide](https://serverless.com/framework/docs/providers/azure/guide/quickstart/) and when running the the first `serverless deploy` command I get the following:

`Serverless: Packaging service...
Serverless: Logging in to Azure

  Type Error ---------------------------------------------

     Cannot read property 'tokenCache' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'tokenCache' of undefined
    at authenticate.then (/Users/yaron.hersh/work/guyg/apriltex-azfunc-dblist/node_modules/az-login/index.js:209:40)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:253:17)
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)`

My enviroment setup is the as the guide suggested.

`serverless --version` : 1.12.1
`node`: v6.10.2

Thanks

**Comment by lostintangent** [comment]
@yhersh Thanks for filing this bug report! I was able to repro this issue by setting an invalid value for one of the four env vars outlined in the getting started guide. I'm not sure whether that is exactly what you're experiencing, but it's definitely a bug that I'll fix ASAP.

Could you double-check that your subscription ID, client ID, client secret and tenant ID env vars are all set correctly? Thanks!

**Comment by lostintangent** [comment]
@yhersh I fixed the issue I mentioned previously and published an update. That said, that fix will simply make the error more friendly if the env vars you set contain invalid credentials (e.g. there's a typo in the client ID, the service principal is expired), so if that isn't the issue, then I'll need to investigate it further.

**Comment by sandeep-paliwal** [comment]
I am also having similar issue although I have set env variables correctly.

> TypeError: Cannot read property 'tokenCache' of undefined
    at authenticate.then (/Users/spaliwal/work/performance/serverless-performance/serverless-performance/node_modules/az-login/index.js:209:40)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
From previous event:
    at PluginManager.run (/Users/spaliwal/work/performance/serverless-performance/serverless-performance/node_modules/serverless/lib/classes/PluginManager.js:160:22)
    at Serverless.run (/Users/spaliwal/work/performance/serverless-performance/serverless-performance/node_modules/serverless/lib/Serverless.js:91:31)
    at serverless.init.then (/Users/spaliwal/work/performance/serverless-performance/serverless-performance/node_modules/serverless/bin/serverless:23:50)
 Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
  Please report this error. We think it might be a bug.
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.2
     Serverless Version: 1.7.0
/Users/sp/work/performance/serverless-performance/serverless-performance/index.js:18
          throw new Error('Function deployment failed with code ' + deployCode);

**Comment by lostintangent** [comment]
This issue should now be resolved. Please re-open it if you experience it again. Thanks!

**Comment by ropstah** [comment]
Issue is still present -> wrong error message. It should state something like: invalid principal configuration, or invalid clientId if possible.

In my case it was an invalid `azureServicePrincipalClientId` environment setting. 

The description on this page is not clear: https://serverless.com/framework/docs/providers/azure/guide/credentials/. It says to enter the "name" at 5. However it is unclear from the returned principal variables which one the name is. I guessed the `name` (being something like http://the-name). 

However it needs to be the `appId`!

Changing the `azureServicePrincipalClientId` to the `appId` value made it work.

**Comment by ropstah** [comment]
Step 5 from the [Azure guide](https://serverless.com/framework/docs/providers/azure/guide/credentials/) is a little unclear as to whether or not the single quotes should be included around the environment variables. Also it is unclear that `appId` should be used as value for the `azureServicePrincipalClientId` environment variable.

**Comment by ropstah** [comment]
Doing either of those still gives the error message "Cannot read property 'tokenCache' of undefined" whereas it could perhaps be more descriptive.
