### ISSUE TITLE
unable to login to azure using serverless deploy

### ISSUE THREAD

**Issue by si458** [serverless/serverless-azure-functions#74]
What went wrong? serverless wont login to azure
What did you expect should have happened? to login to azure and deploy
What was the config you used? default, no chances at all

SiMacBookPro:MyPingCheck Simon$ serverless deploy -v
Serverless: Packaging service...
Serverless: Logging in to Azure
Serverless: Paste this code (copied to your clipboard) into the launched browser, and complete the authentication process: XXXXXXXX

after the browser opens and i login and says close window, the serverless command just seems to sit there and nothing happens

Serverless Framework Version you're using: 1.15.1
Operating System: OSX 10.12.5

**Comment by joefiorini** [comment]
Same error here, same configuration except I have Serverless 1.15.3.

**Comment by lostintangent** [comment]
@si458 @joefiorini This has been resolved in an upstream dependency, so if you re-install the `serverless-azure-functions` NPM module, that should pick up the fix here. Let me know if that works for you.

**Comment by vjrantal** [comment]
@lostintangent I had the same issue and re-installing did not solve it. After a bit of debugging, I realized it is because in `package.json` the dependency is defined like this:

```
"az-login": "^0.1.7"
```

At the same time, the latest version (with the fix) is `0.2.3`, but because the version has zero as the major version, the latest package version isn't installed. This is because major version zero is a bit of a special case https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004.

I can confirm that for me, this issue went away when I forced the update to version `0.2.3`. To make the fix easily available for others, the dependency range should be changed in the `package.json` file of this repository so that `0.2.x` releases of `az-login` would get installed.

**Comment by si458** [comment]
@vjrantal can you explain how you got it to work as i still cant get it to work :(

**Comment by vjrantal** [comment]
@si458 The steps I took are something like below:

```
cd <my-serverless-project-folder>
cd node_modules/serverless-azure-functions
npm install az-login@latest
grep version node_modules/az-login/package.json
// should print out a version equal or greater than 0.2.3
```

**Comment by si458** [comment]
@vjrantal your method didnt work for me as it keps quiting the deploy after it started

however this way worked for me, but not i get another error instead ?

`cd <your project>`
`cd node_modules/serverless-azure-functions`
`edit package.json and change "az-login": "^0.1.7" to  "az-login": "^0.2.0"`

and the error i now get is
` Long running operation failed with error: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.`
